# Generated by go2rpm
%bcond_with check

# https://github.com/uber-go/atomic
%global goipath         go.uber.org/atomic
%global forgeurl        https://github.com/uber-go/atomic

%global provider        github
%global provider_tld    com
%global project         uber-go
%global repo            atomic
# https://github.com/golang/sys
%global provider_prefix %{provider}.%{provider_tld}/%{project}/%{repo}
%global import_path     go.uber.org/atomic
# %global commit          ac6580df4449443a05718fd7858c1f91ad5f8d20
%global shortcommit     %(c=%{commit}; echo ${c:0:7})

Version:                1.5.1


%global common_description %{expand:
Package Atomic provides simple wrappers around numerics to enforce atomic
access.}

%global golicenses      LICENSE.txt
%global godocs          README.md

Name:           golang-uber-atomic
Release:        1%{?dist}
Summary:        Wrapper types for sync/atomic which enforce atomic access

License:        MIT
URL:            https://%{provider_prefix}
Source0:        https://%{provider_prefix}/archive/v%{release}.tar.gz#/%{repo}-%{version}.tar.gz

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

Provides: golang(go.uber.org/atomic)

%description
%{common_description}

%gopkg

%prep
%setup -q -n %{repo}-%{version}

%install
# source codes for building projects
install -d -p %{buildroot}/%{gopath}/src/%{import_path}/
echo "%%dir %%{gopath}/src/%%{import_path}/." >> devel.file-list
# find all *.s and generate devel.file-list
for file in $(find . -iname "*.s") ; do
    echo "%%dir %%{gopath}/src/%%{import_path}/$(dirname $file)" >> devel.file-list
    install -d -p %{buildroot}/%{gopath}/src/%{import_path}/$(dirname $file)
    cp -pav $file %{buildroot}/%{gopath}/src/%{import_path}/$file
    echo "%%{gopath}/src/%%{import_path}/$file" >> devel.file-list
done
# find all *.c and generate devel.file-list
for file in $(find . -iname "*.c") ; do
    echo "%%dir %%{gopath}/src/%%{import_path}/$(dirname $file)" >> devel.file-list
    install -d -p %{buildroot}/%{gopath}/src/%{import_path}/$(dirname $file)
    cp -pav $file %{buildroot}/%{gopath}/src/%{import_path}/$file
    echo "%%{gopath}/src/%%{import_path}/$file" >> devel.file-list
done
# find all *.go but no *_test.go files and generate devel.file-list
for file in $(find . -iname "*.go" \! -iname "*_test.go") ; do
    echo "%%dir %%{gopath}/src/%%{import_path}/$(dirname $file)" >> devel.file-list
    install -d -p %{buildroot}/%{gopath}/src/%{import_path}/$(dirname $file)
    cp -pav $file %{buildroot}/%{gopath}/src/%{import_path}/$file
    echo "%%{gopath}/src/%%{import_path}/$file" >> devel.file-list
done

sort -u -o devel.file-list devel.file-list


%if %{with check}
%check
%gocheck
%endif

%files -f devel.file-list
%license LICENSE.txt
%doc README.md

%changelog
* Sun Feb 16 2020 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 1.5.1-1
- Update to latest version

* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.4.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.4.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Fri Apr 26 21:17:34 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 1.4.0-1
- Release 1.4.0

* Thu Mar 14 2019 Robert-André Mauchin <zebob.m@gmail.com> - 1.3.2-1
- First package for Fedora
